[build]
  command = "npm run build"
  publish = "dist"

# Redirects for SEO
[[redirects]]
  from = "/sitemap.xml"
  to = "/.netlify/functions/sitemap"
  status = 200
  force = true

[functions]
  directory = "netlify/functions"


[[scheduled_functions]]
  function = "keep-alive"
  cron = "0 */2 * * *"


[dev]
  command = "npm run dev"
  targetPort = 8081
  port = 8888